spring:
  application:
    name: block-stream

server:
  port: 9000

aergo:
  server:
    hostname: testnet-api.aergo.io
    port: 7845

  account:
    from:
      address:
      wif:
      password:
    to:
      address:
